name: iot
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  async: ^2.2.0
  grpc:  ^2.3.0
  protobuf: ^1.0.1
  crypto: ^2.1.4
  googleapis_auth: ^0.2.7
  meta: ^1.1.6
  http: ^0.12.0
  http2: ^1.0.0
  flutter_screenutil: ^2.3.1
  sqflite: ^1.3.1
  table_calendar: ^2.2.3
  flutter_bloc: ^6.0.1
  top_sheet: ^0.0.4
  path_provider: ^1.6.11
  rflutter_alert: ^1.0.3
  encrypt: ^4.0.2
  image_picker: ^0.6.7+4
  intl: ^0.16.1
  search_widget: ^1.0.2
  provider: ^4.3.2
  consumer: ^2.0.2
  liquid_pull_to_refresh: ^2.0.0
  font_awesome_flutter: 8.5.0
  pagination_view: ^1.0.3+2
  faker: ^1.2.1
  permission_handler: ^4.4.0
  shared_preferences: ^0.5.12+4
  dio: ^3.0.10
  device_info: ^1.0.0
  path: ^1.7.0
  random_string: ^2.1.0
  rxdart: ^0.24.1
  flutter_image: ^3.0.0
  socket_io_client: ^0.9.12
  pointycastle: ^2.0.0
  syncfusion_flutter_gauges: ^18.3.53

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image_01.png
    - assets/image_02.png
    - assets/logo.png
    - assets/logo2.png
    - assets/dp_default.png
    - assets/avatar.png
    - assets/account_settings.png
    - assets/profile-pics/
    - assets/emotions/
    - assets/certs/
    - assets/ph.png
    - assets/ec.png
    - assets/certs/privateKey.pem
    - assets/certs/publicKey.pem
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/CustomIcons.ttf

    - family: Poppins-Bold
      fonts:
        - asset: assets/Poppins-Bold.ttf

    - family: Poppins-Medium
      fonts:
        - asset: assets/Poppins-Medium.ttf
    - family: Montserrat
      fonts:
        - asset: assets/Montserrat/Montserrat-Black.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 600
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 200
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 300

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
